spring.application.name=smartfarming-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret = Bsc_final_year_project_for_Ben_Akua_and_Desmond_super_secure_secret_key_2026
jwt.expiration = 86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080